version: "3.6"
services:
  weathy:
    image: techblog/weathy
    container_name: weathy
    restart: always
    environment:
      - NOTIFIERS= #Apprise notifiers
      - TZ=Asia/Jerusalem
      - LOCATION=
      - LANGUAGE=
      - SCHEDULE=
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
